// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ChangeTheme: typeof import('./../views/components/ChangeTheme.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    DownloadCv: typeof import('./../views/components/DownloadCv.vue')['default']
    Image: typeof import('primevue/image')['default']
    MyButton: typeof import('./../views/components/MyButton.vue')['default']
    MyLinks: typeof import('./../views/components/MyLinks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutesButtons: typeof import('./../views/components/RoutesButtons.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    TheFooter: typeof import('./../views/components/TheFooter.vue')['default']
    TheHeader: typeof import('./../views/components/TheHeader.vue')['default']
  }
}
