// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11.09.2024 17:50:31
const configMerger = require("C:/Users/evane/Desktop/MyProjects/Portfolio_Website/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.1_rollup@3.29.4/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/evane/Desktop/MyProjects/Portfolio_Website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/evane/Desktop/MyProjects/Portfolio_Website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/evane/Desktop/MyProjects/Portfolio_Website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/evane/Desktop/MyProjects/Portfolio_Website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/evane/Desktop/MyProjects/Portfolio_Website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/evane/Desktop/MyProjects/Portfolio_Website/plugins/**/*.{js,ts,mjs}","C:/Users/evane/Desktop/MyProjects/Portfolio_Website/stores/**/*.{js,ts,mjs}","C:/Users/evane/Desktop/MyProjects/Portfolio_Website/pages/**/*.{js,ts,mjs}","C:/Users/evane/Desktop/MyProjects/Portfolio_Website/components/**/*.{js,ts,mjs}","C:/Users/evane/Desktop/MyProjects/Portfolio_Website/composables/**/*.{js,ts,mjs}","C:/Users/evane/Desktop/MyProjects/Portfolio_Website/utils/**/*.{js,ts,mjs}","C:/Users/evane/Desktop/MyProjects/Portfolio_Website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/evane/Desktop/MyProjects/Portfolio_Website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/evane/Desktop/MyProjects/Portfolio_Website/app.config.{js,ts,mjs}"] }));

module.exports = config
